---
title: Remove bloatware
privilege: TrustedInstaller

actions:
  - !writeStatus: {status: 'QOL Fixes'}

  # classic context menu
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32', value: '', type: REG_SZ, data: ''}

  # ctfmon bug fix
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'ctfmon', type: REG_SZ, data: 'C:\Windows\System32\ctfmon.exe'}

  # visual effects
  - !registryValue:
    path: 'HKCU\Control Panel\Desktop'
    value: 'FontSmoothing'
    data: '2'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\Control Panel\Desktop'
    value: 'UserPreferencesMask'
    data: '9012038010000000'
    type: REG_BINARY
  - !registryValue:
    path: 'HKCU\Control Panel\Desktop'
    value: 'DragFullWindows'
    data: '1'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\Control Panel\Desktop\WindowMetrics'
    value: 'MinAnimate'
    data: '0'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ListviewAlphaSelect'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'IconsOnly'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'TaskbarAnimations'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ListviewShadow'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects'
    value: 'VisualFXSetting'
    data: '3'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\DWM'
    value: 'EnableAeroPeek'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\DWM'
    value: 'AlwaysHibernateThumbnails'
    data: '0'
    type: REG_DWORD

  # mouse accel
  - !registryValue:
    path: 'HKCU\Control Panel\Mouse'
    value: 'MouseSpeed'
    data: '0'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\Control Panel\Mouse'
    value: 'MouseThreshold1'
    data: '0'
    type: REG_SZ
  - !registryValue:
    path: 'HKCU\Control Panel\Mouse'
    value: 'MouseThreshold2'
    data: '0'
    type: REG_SZ

  # disable ads in settings
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\ValueBanner.IdealStateFeatureControlProvider'
    value: 'ActivationType'
    data: '0'
    type: REG_DWORD

  # dark mode
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize'
    value: 'AppsUseLightTheme'
    data: '0'
    type: REG_DWORD

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize'
    value: 'SystemUsesLightTheme'
    data: '0'
    type: REG_DWORD
    
  - !registryValue:
    path: 'HKCU\Control Panel\Desktop'
    value: 'Wallpaper'
    data: 'C:\WINDOWS\web\wallpaper\Windows\img19.jpg'
    type: REG_SZ
