---
title: Remove bloatware
privilege: TrustedInstaller

# thanks atlas os
actions:
  - !writeStatus: {status: 'Removing bloatware'}

  - !taskKill: {name: 'ms-teams*', ignoreErrors: true}
  - !appx: {name: 'MSTeams*', type: family}

  - !appx: {name: 'Microsoft.Copilot*', type: family}
  - !appx: {name: 'Clipchamp.Clipchamp*', type: family}
  - !appx: {name: 'Disney.37853FC22B2CE*', type: family}
  - !appx: {name: 'SpotifyAB.SpotifyMusic*', type: family}
  - !appx: {name: 'Microsoft.549981C3F5F10*', type: family}
  - !appx: {name: 'microsoft.windowscommunicationsapps*', type: family}
  - !appx: {name: 'Microsoft.MSPaint*', type: family}
  - !appx: {name: 'Microsoft.Getstarted*', type: family}
  - !appx: {name: 'MicrosoftCorporationII.MicrosoftFamily*', type: family}
  - !appx: {name: 'Microsoft.MixedReality.Portal*', type: family}
  - !appx: {name: 'Microsoft.Windows.DevHome*', type: family}
  - !appx: {name: 'Microsoft.BingWeather*', type: family}
  - !appx: {name: 'Microsoft.BingNews*', type: family}
  - !appx: {name: 'Microsoft.BingSearch*', type: family}
  - !appx: {name: 'Microsoft.OutlookForWindows*', type: family}
  - !appx: {name: 'Microsoft.GetHelp*', type: family}
  - !appx: {name: 'Microsoft.Microsoft3DViewer*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftOfficeHub*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftSolitaireCollection*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftStickyNotes*', type: family}
  - !appx: {name: 'Microsoft.Office.OneNote*', type: family}
  - !appx: {name: 'Microsoft.People*', type: family}
  - !appx: {name: 'Microsoft.PowerAutomateDesktop*', type: family}
  - !appx: {name: 'Microsoft.SkypeApp*', type: family}
  - !appx: {name: 'Microsoft.Todos*', type: family}
  - !appx: {name: 'Microsoft.WindowsAlarms*', type: family}
  - !appx: {name: 'Microsoft.WindowsCamera*', type: family}
  - !appx: {name: 'Microsoft.WindowsFeedbackHub*', type: family}
  - !appx: {name: 'Microsoft.WindowsMaps*', type: family}
  - !appx: {name: 'Microsoft.WindowsSoundRecorder*', type: family}

  - !powerShell:
    command: |
      Get-AppxPackage Microsoft.YourPhone* | Remove-AppxPackage
      Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq 'Microsoft.YourPhone' } | Remove-AppxProvisionedPackage -Online
    runas: currentUserElevated
    wait: true

  # XBOX
  - !appx: {name: 'Microsoft.XboxApp*', type: family, option: 'xbox-remove'}
  - !appx: {name: 'Microsoft.Xbox.TCUI*', type: family, option: 'xbox-remove'}
  - !appx: {name: 'Microsoft.XboxGameOverlay*', type: family, option: 'xbox-remove'}
  - !appx: {name: 'Microsoft.XboxGameCallableUI*', type: family, option: 'xbox-remove'}
  - !appx: {name: 'Microsoft.XboxSpeechToTextOverlay*', type: family, option: 'xbox-remove'}
  - !appx: {name: 'Microsoft.XboxGamingOverlay*', type: family, option: 'xbox-remove'}

  - !writeStatus: {status: 'Removing Microsoft Edge'}
  - !powerShell:
    command: '& """.\RemoveEdge.ps1""" -UninstallEdge -RemoveEdgeData -KeepAppX -NonInteractive'
    runas: currentUserElevated
    wait: true
    exeDir: true
  - !appx: {name: 'Microsoft.MicrosoftEdge_8wekyb3d8bbwe', type: family, option: 'uninstall-edge'}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe', operation: add, option: 'uninstall-edge'}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge_8wekyb3d8bbwe', operation: add, option: 'uninstall-edge'}

  - !writeStatus: {status: 'Removing OneDrive'}
  - !run: {exeDir: true, exe: 'REMONEDRIVE.cmd'}

  - !writeStatus: {status: 'Disabling search on web'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowSearchToUseLocation', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search', value: 'BingSearchEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings', value: 'IsAADCloudSearchEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings', value: 'IsDeviceSearchHistoryEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings', value: 'IsMSACloudSearchEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings', value: 'SafeSearchMode', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'ConnectedSearchUseWeb', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'DisableWebSearch', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'EnableDynamicContentInWSB', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SearchSettings', value: 'IsDynamicSearchBoxEnabled', type: REG_DWORD, data: '0'}

  - !writeStatus: {status: 'Clearing AppX caches'}
  - !appx: {operation: clearCache, name: '*MicrosoftWindows.Client.CBS*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.Search*'}
  - !appx: {operation: clearCache, name: '*Microsoft.Windows.SecHealthUI*'}

  - !taskKill: {name: 'StartMenuExperienceHost', ignoreErrors: true}
  
  - !powerShell:
    command: '.\CLEANSTART.ps1'
    exeDir: true
    wait: true

  - !appx: {operation: clearCache, name: 'Microsoft.Windows.StartMenuExperienceHost*'}