name: Build Archive

on:
  push:
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install 7-Zip
      shell: pwsh
      run: |
        choco install 7zip -y
    
    - name: Create Archive
      shell: pwsh
      run: |
        7z a -p"malte" optiwin.apbx ./Playbook/*
    
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: playbook-archive
        path: optiwin.apbx
